### ISSUE TITLE
Cannot process event as "jdbcConnector" is stopped

### ISSUE THREAD

**Issue by jasonchw** [mulesoft/munit#141]
I was trying to test a flow with JDBC outbound endpoint in Studio, but got error "Cannot process event as "jdbcConnector" is stopped".

The following is the mule config,
```
    <spring:beans>
        <spring:bean id="h2DataSource" class="org.enhydra.jdbc.standard.StandardDataSource" destroy-method="shutdown">
            <spring:property name="driverName" value="org.h2.Driver" />
            <spring:property name="url" value="jdbc:h2:mem:test" />
            <spring:property name="user" value="sa" />
            <spring:property name="password" value="" />
        </spring:bean>
    </spring:beans>

    <jdbc-ee:connector name="jdbcConnector" dataSource-ref="h2DataSource" doc:name="Database">
        <jdbc-ee:query key="lookupJob" value="SELECT * FROM jobtitlelookup WHERE jobtitleid = #[variable:jobid]"></jdbc-ee:query>
    </jdbc-ee:connector>

    <flow name="jdbcFlow" doc:name="jdbcFlow">
        <set-variable variableName="jobid" value="123456" doc:name="Variable" />
        <jdbc-ee:outbound-endpoint exchange-pattern="one-way" queryTimeout="-1" doc:name="Database" connector-ref="jdbcConnector"
            queryKey="lookupJob">
            <jdbc-ee:transaction action="JOIN_IF_POSSIBLE" />
        </jdbc-ee:outbound-endpoint>
        <logger level="INFO" doc:name="Logger" message="#[payload]" />
    </flow>
```

The JavaTest class,
```
package org.mule.java;

import static junit.framework.Assert.assertEquals;
import static org.mule.munit.common.mocking.Attribute.attribute;

import org.junit.Test;
import org.mule.api.MuleEvent;
import org.mule.munit.runner.functional.FunctionalMunitSuite;

public class JdbcTest extends FunctionalMunitSuite {
    @Override
    protected String getConfigResources() {
        return "jdbc.xml";
    }

    @Test
    public void testJdbcFlow() throws Exception {
        MuleEvent eventResult = runFlow("jdbcFlow", testEvent(null));
        assertEquals("pass munitSubFlow", eventResult.getMessage().getPayloadAsString());

        verifyCallOfMessageProcessor("outbound-endpoint").ofNamespace("jdbc-ee")
                .withAttributes(attribute("name").ofNamespace("doc").withValue("Database"))
                .atLeastOnce();
    }
}
```

And the error message from Studio,
```
[12-02 11:32:11] ERROR DefaultMessagingExceptionStrategy [main]: 
********************************************************************************
Message               : Cannot process event as "jdbcConnector" is stopped
Type                  : org.mule.api.lifecycle.LifecycleException
Code                  : MULE_ERROR-166
JavaDoc               : http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/lifecycle/LifecycleException.html
********************************************************************************
Exception stack is:
1. Cannot process event as "jdbcConnector" is stopped (org.mule.api.lifecycle.LifecycleException)
  org.mule.lifecycle.processor.ProcessIfStartedMessageProcessor:42 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/lifecycle/LifecycleException.html)
********************************************************************************
Root Exception stack trace:
org.mule.api.lifecycle.LifecycleException: Cannot process event as "jdbcConnector" is stopped
	at org.mule.lifecycle.processor.ProcessIfStartedMessageProcessor.handleUnaccepted(ProcessIfStartedMessageProcessor.java:42)
	at org.mule.processor.AbstractFilteringMessageProcessor.process(AbstractFilteringMessageProcessor.java:48)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47)
	at org.mule.endpoint.DefaultOutboundEndpoint.process(DefaultOutboundEndpoint.java:96)
	at org.mule.munit.common.endpoint.MockOutboundEndpoint.process(MockOutboundEndpoint.java:231)
	at org.mule.munit.common.endpoint.MockOutboundEndpoint$$FastClassByCGLIB$$cc824ca5.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
	at org.mule.munit.common.mp.WrapperMunitMessageProcessorInterceptor.invokeSuper(WrapperMunitMessageProcessorInterceptor.java:71)
	at org.mule.munit.common.mp.MunitMessageProcessorInterceptor.process(MunitMessageProcessorInterceptor.java:59)
	at org.mule.munit.common.mp.WrapperMunitMessageProcessorInterceptor.intercept(WrapperMunitMessageProcessorInterceptor.java:46)
	at org.mule.munit.common.endpoint.MockOutboundEndpoint$$EnhancerByMUNIT$$cc824ca5.process(<generated>)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47)
	at org.mule.processor.AsyncInterceptingMessageProcessor.process(AsyncInterceptingMessageProcessor.java:101)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47)
	at org.mule.interceptor.AbstractEnvelopeInterceptor.process(AbstractEnvelopeInterceptor.java:55)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47)
	at org.mule.processor.AbstractFilteringMessageProcessor.process(AbstractFilteringMessageProcessor.java:44)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47)
	at org.mule.construct.AbstractPipeline$1.process(AbstractPipeline.java:112)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.exe...
********************************************************************************
```

**Comment by damiansima** [comment]
Hi @jasonchw 
Sorry for the delay I forgot about this.
Here is an example on how to mock a JDBC outbound endpoint in java. Bear in mind that MUNIT has to be set to work in its default parameters, that is, mocking connectors and endpoints. 
Please also notice this applies fro the origin JDBC transport. 

Your **production-code**
```xml
<jdbc:connector name="jdbcConnectorInbound"  dataSource-ref="jdbcDataSource">
	<jdbc:query key="lookupJob" value="SELECT * FROM jobtitlelookup WHERE jobtitleid = #[flowVars['jobid']]"/>
</jdbc:connector>


<flow name="demoFlow">
 <jdbc:outbound-endpoint connector-ref="jdbcConnectorInbound" queryKey="lookupJob" exchange-pattern="request-response"/>
</flow>

```

Your Java **test-code**
```java
public class JavaTest extends FunctionalMunitSuite
{
	@Override
    protected String getConfigResources()
    {
        return "your-actual-mule-config.xml";
    }

 	@Test
    public void demoTest() throws Exception
    {
  whenEndpointWithAddress("jdbc://lookupJob").thenReturn(muleMessageWithPayload(buildPayloadMethod()));
        runFlow("demoFlow", testEvent("Hello world!"));
		
		//...
        // Run assertions & validations
	}
}
```

Let me know if it helps ;)

Cheers!

**Comment by jasonchw** [comment]
Hi @damiansima,

Thanks, it is really helpful.

Jason
