### ISSUE TITLE
simple MUnit failing with a big stack trace 

### ISSUE THREAD

**Issue by jamesontriplett** [mulesoft/munit#153]
I'm trying my first munit test on a reletively simple flow that implements an XML validator.  I basically copied a working Junit test and adapted it for Munit. Running MUnit 3.5-M3-SNAPSHOT

```java
public class OrderEcommerceMUnitTest extends FunctionalMunitSuite{

	String validMessage2;
	
	@Before
	public void initMessage() throws IOException {

		validMessage2 = IOUtils.toString(new ClassPathResource(
				"order1.xml").getInputStream());
	}
	
	@Override
	protected String getConfigResources() {
		return "OrderEcommerceToOms.xml";
	}
	
    @Test
    public void validateEchoFlow() throws Exception {
        MuleEvent resultEvent = runFlow("receiveOrder", testEvent(validMessage2));

        assertEquals(validMessage2, resultEvent.getMessage().getPayloadAsString());
    }
```

Here's the lovely stack trace.  It doesn't make any sense to me about "countryCodes"  there are no countryCodes in my application, flows, associated flows, input parameters.
```
java.lang.RuntimeException: org.mule.api.config.ConfigurationException: Error creating bean with name 'countryCodes': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property '__MUNIT_LINE_NUMBER' of bean class [org.springframework.beans.factory.config.PropertiesFactoryBean$$EnhancerByMUNIT$$c0817251]: Bean property '__MUNIT_LINE_NUMBER' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter? (org.mule.api.lifecycle.InitialisationException)
	at org.mule.munit.runner.functional.FunctionalMunitSuite.<init>(FunctionalMunitSuite.java:74)
	at com.rh.mule.OrderEcommerceMUnitTest.<init>(OrderEcommerceMUnitTest.java:24)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:178)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:227)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:224)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.mule.api.config.ConfigurationException: Error creating bean with name 'countryCodes': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property '__MUNIT_LINE_NUMBER' of bean class [org.springframework.beans.factory.config.PropertiesFactoryBean$$EnhancerByMUNIT$$c0817251]: Bean property '__MUNIT_LINE_NUMBER' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter? (org.mule.api.lifecycle.InitialisationException)
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:49)
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69)
	at org.mule.context.DefaultMuleContextFactory$1.configure(DefaultMuleContextFactory.java:84)
	at org.mule.context.DefaultMuleContextFactory.doCreateMuleContext(DefaultMuleContextFactory.java:217)
	at org.mule.context.DefaultMuleContextFactory.createMuleContext(DefaultMuleContextFactory.java:76)
	at org.mule.munit.runner.MuleContextManager.createMule(MuleContextManager.java:114)
	at org.mule.munit.runner.functional.FunctionalMunitSuite.<init>(FunctionalMunitSuite.java:63)
	... 24 more
Caused by: org.mule.api.lifecycle.InitialisationException: Error creating bean with name 'countryCodes': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property '__MUNIT_LINE_NUMBER' of bean class [org.springframework.beans.factory.config.PropertiesFactoryBean$$EnhancerByMUNIT$$c0817251]: Bean property '__MUNIT_LINE_NUMBER' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.mule.registry.AbstractRegistry.initialise(AbstractRegistry.java:113)
	at org.mule.config.spring.SpringXmlConfigurationBuilder.createSpringRegistry(SpringXmlConfigurationBuilder.java:135)
	at org.mule.config.spring.SpringXmlConfigurationBuilder.doConfigure(SpringXmlConfigurationBuilder.java:90)
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:43)
	... 30 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'countryCodes': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property '__MUNIT_LINE_NUMBER' of bean class [org.springframework.beans.factory.config.PropertiesFactoryBean$$EnhancerByMUNIT$$c0817251]: Bean property '__MUNIT_LINE_NUMBER' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1454)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1159)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:633)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.mule.config.spring.SpringRegistry.doInitialise(SpringRegistry.java:86)
	at org.mule.registry.AbstractRegistry.initialise(AbstractRegistry.java:105)
	... 33 more
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property '__MUNIT_LINE_NUMBER' of bean class [org.springframework.beans.factory.config.PropertiesFactoryBean$$EnhancerByMUNIT$$c0817251]: Bean property '__MUNIT_LINE_NUMBER' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:1043)
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:903)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:75)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:57)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1451)
	... 45 more
```

**Comment by damiansima** [comment]
Hi there @jamesontriplett,

I've seen this before and it's related to a bean that Munit is not being able to mock.

There may be a few reasons for that but to know for sure I need to check the application you're working on.

Would you mind sharing your application with me.

Cheers!
