### ISSUE TITLE
Subflow with Async call gives error while running munit

### ISSUE THREAD

**Issue by VikramAhuja** [mulesoft/munit#189]
Hi,

we have a folowwing sub flow with Async call

<sub-flow name="xxx-subflow">
.....
<async doc:name="Async">
            <flow-ref name="yyy-create-subflow" doc:name="yyy-create-subflow"/>
</async>
</sub-flow>

so when we run the munit 

MuleEvent result = runFlow("xxx-subflow", testEvent(message));

for this sub flow we get following error

java.lang.IllegalArgumentException: FlowConstruct cannot be null
	at org.mule.processor.AsyncDelegateMessageProcessor.validateFlowConstruct(AsyncDelegateMessageProcessor.java:110)
	at org.mule.processor.AsyncDelegateMessageProcessor.initialise(AsyncDelegateMessageProcessor.java:80)
	at org.mule.processor.AsyncDelegateMessageProcessor$$FastClassByCGLIB$$8d55810d.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
	at org.mule.munit.common.mp.WrapperMunitMessageProcessorInterceptor.invokeSuper(WrapperMunitMessageProcessorInterceptor.java:71)
	at org.mule.munit.common.mp.WrapperMunitMessageProcessorInterceptor.invokeSuper(WrapperMunitMessageProcessorInterceptor.java:63)
	at org.mule.munit.common.mp.WrapperMunitMessageProcessorInterceptor.intercept(WrapperMunitMessageProcessorInterceptor.java:49)
	at org.mule.processor.AsyncDelegateMessageProcessor$$EnhancerByMUNIT$$8d55810d.initialise(<generated>)
	at org.mule.processor.chain.AbstractMessageProcessorChain.initialise(AbstractMessageProcessorChain.java:82)
	at org.mule.processor.chain.AbstractMessageProcessorChain$$FastClassByCGLIB$$38c17d88.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
	at org.mule.munit.common.mp.WrapperMunitMessageProcessorInterceptor.invokeSuper(WrapperMunitMessageProcessorInterceptor.java:71)
	at org.mule.munit.common.mp.WrapperMunitMessageProcessorInterceptor.invokeSuper(WrapperMunitMessageProcessorInterceptor.java:63)
	at org.mule.munit.common.mp.WrapperMunitMessageProcessorInterceptor.intercept(WrapperMunitMessageProcessorInterceptor.java:49)
	at org.mule.processor.chain.SubflowInterceptingChainLifecycleWrapper$$EnhancerByMUNIT$$c8ca2508.initialise(<generated>)
	at org.mule.munit.runner.functional.FunctionalMunitSuite.initialiseSubFlow(FunctionalMunitSuite.java:269)
	at org.mule.munit.runner.functional.FunctionalMunitSuite.runFlow(FunctionalMunitSuite.java:259)
	at com.xxxx.common.integrations.functional.XxxFlowTest.testxxxCreateFlow_NewPayload(XXXFlowTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

we are using 3.6.0-BETA version of munit. we had same issue with 3.5 version of munit.

**Comment by damiansima** [comment]
Hi @VikramAhuja, 

We are aware of this problem and we have an open issue to fix it. 
I can offer a work around though. 

If you are willing to code your test in XML the problem should solve it self. If not the only other work around is to have a flow (not a sub-flow) with a flow-ref to you actual sub-flow.
Finally instead of running your sub-flow from your test you'll have to run you flow. 

I know it's a pain but currently it's the only way to solve your problem.

Cheers!

**Comment by VikramAhuja** [comment]
@damiansima 
Thanks for your response. 

can you tell me in which release this issue with get fixed? any planned release?

**Comment by damiansima** [comment]
Future release(?) 
It's on the pipeline but I don't have a firm date just yet, I'm sorry. 
We have other, more pressing, issues to deal with before this one.

**Comment by VikramAhuja** [comment]
ok. can you give me issue number so that i can keep a track on it?

**Comment by damiansima** [comment]
Sure:  https://www.mulesoft.org/jira/browse/MU-260

**Comment by VikramAhuja** [comment]
thanks. can you link this issue witn MU-260? i can not do it so asking you to do it.
