### ISSUE TITLE
Mock SFTP Endpoint

### ISSUE THREAD

**Issue by jon-elliott** [mulesoft/munit#191]
I am trying to mock an SFTP outbound endpoint - i have followed the FTP-server documentation but it appears outdated as the dependency in 3.6.0 is now module based. 
Every time i try to test the flow i get an exception:
Exception stack is:
1. Cannot process event as "SFTP" is stopped (org.mule.api.lifecycle.LifecycleException)
  org.mule.lifecycle.processor.ProcessIfStartedMessageProcessor:38 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/lifecycle/LifecycleException.html)
--------------------------------------------------------------------------------
Root Exception stack trace:
org.mule.api.lifecycle.LifecycleException: Cannot process event as "SFTP" is stopped
	at org.mule.lifecycle.processor.ProcessIfStartedMessageProcessor.handleUnaccepted(ProcessIfStartedMessageProcessor.java:38)
	at org.mule.processor.AbstractFilteringMessageProcessor.process(AbstractFilteringMessageProcessor.java:44)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)
    + 3 more (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)

Munit test case:

<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:ftpserver="http://www.mulesoft.org/schema/mule/ftpserver" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:mclient="http://www.mulesoft.org/schema/mule/mclient" 
	xmlns="http://www.mulesoft.org/schema/mule/core" 
	xmlns:mock="http://www.mulesoft.org/schema/mule/mock" 
	xmlns:munit="http://www.mulesoft.org/schema/mule/munit" 
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" 
	xmlns:spring="http://www.springframework.org/schema/beans" 
	xmlns:core="http://www.mulesoft.org/schema/mule/core" version="EE-3.6.2" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-current.xsd
http://www.mulesoft.org/schema/mule/mock http://www.mulesoft.org/schema/mule/mock/current/mule-mock.xsd
http://www.mulesoft.org/schema/mule/munit http://www.mulesoft.org/schema/mule/munit/current/mule-munit.xsd
http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/mclient http://www.mulesoft.org/schema/mule/mclient/current/mule-mclient.xsd
http://www.mulesoft.org/schema/mule/ftpserver http://www.mulesoft.org/schema/mule/ftpserver/current/mule-ftpserver.xsd">

	<context:property-placeholder location="test.properties"/>
    <munit:config name="munit" doc:name="Munit configuration"/>
    <mock:config name="mock_midas_outbound_flow" doc:name="Mock configuration"/>

    
    <spring:beans>
        <spring:import resource="classpath:midas_outbound_flow.xml"/>
    </spring:beans>
    <ftpserver:config name="FTP_Server" port="3002" secure="true" doc:name="FTP Server"/>
	 <munit:before-suite name="before.suite" description="Starting FTP server">
	          <ftpserver:start-server config-ref="FTP_Server"/>
	</munit:before-suite>
 	<munit:test name="midas_outbound_flow_munit_SuccessTest" description="Test">
 		<munit:set payload-ref="#[getResource('payload.json').asString() ]" doc:name="Set Message"/>
 		<flow-ref name="MIDAS_Outbound_Flow" doc:name="Flow-ref to cemar_inbound_flowFlow"/>
 	</munit:test>

</mule>

**Comment by jon-elliott** [comment]
Update: didn't use the SFTP module of munit - i ran i could connect to it but Mule ignored it. I think mule was being a bit and an ass. So i just mocked the endpoint instead.
