### ISSUE TITLE
MUnit not running in Anypoint studio

### ISSUE THREAD

**Issue by jon-elliott** [mulesoft/munit#192]
Every time i try to run an munit from within anypoint studio i get the following error:
Connected to localhost in port 63444
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Applications/AnypointStudio/plugins/org.mule.tooling.server.3.6.2.ee_5.1.1.201504092115/mule/lib/boot/log4j-slf4j-impl-2.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/Jon-Elliott/.m2/repository/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Exception in thread "main" java.lang.RuntimeException: org.mule.api.config.ConfigurationException: Configuration problem: Failed to import bean definitions from URL location [classpath:midas_outbound_flow.xml]
Offending resource: URL [file:/Users/Jon-Elliott/workspace/midas_outbound_flow/target/test-classes/MIDAS_Outbound_Flow_test.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [midas_outbound_flow.xml]; nested exception is java.lang.ArrayIndexOutOfBoundsException: -1 (org.mule.api.lifecycle.InitialisationException)
	at org.mule.munit.runner.mule.MunitSuiteRunner.<init>(MunitSuiteRunner.java:47)
	at org.mule.munit.runner.mule.MunitSuiteRunner.<init>(MunitSuiteRunner.java:36)
	at org.mule.munit.runner.remote.MunitRemoteRunner.run(MunitRemoteRunner.java:40)
	at org.mule.munit.runner.remote.MunitRemoteRunner.main(MunitRemoteRunner.java:143)
Caused by: org.mule.api.config.ConfigurationException: Configuration problem: Failed to import bean definitions from URL location [classpath:midas_outbound_flow.xml]
Offending resource: URL [file:/Users/Jon-Elliott/workspace/midas_outbound_flow/target/test-classes/MIDAS_Outbound_Flow_test.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [midas_outbound_flow.xml]; nested exception is java.lang.ArrayIndexOutOfBoundsException: -1 (org.mule.api.lifecycle.InitialisationException)
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:49)
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69)
	at org.mule.context.DefaultMuleContextFactory$1.configure(DefaultMuleContextFactory.java:84)
	at org.mule.context.DefaultMuleContextFactory.doCreateMuleContext(DefaultMuleContextFactory.java:217)
	at org.mule.context.DefaultMuleContextFactory.createMuleContext(DefaultMuleContextFactory.java:76)
	at org.mule.munit.runner.MuleContextManager.createMule(MuleContextManager.java:100)
	at org.mule.munit.runner.MuleContextManager.startMule(MuleContextManager.java:57)
	at org.mule.munit.runner.mule.MunitSuiteRunner.<init>(MunitSuiteRunner.java:41)
	... 3 more
Caused by: org.mule.api.lifecycle.InitialisationException: Configuration problem: Failed to import bean definitions from URL location [classpath:midas_outbound_flow.xml]
Offending resource: URL [file:/Users/Jon-Elliott/workspace/midas_outbound_flow/target/test-classes/MIDAS_Outbound_Flow_test.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [midas_outbound_flow.xml]; nested exception is java.lang.ArrayIndexOutOfBoundsException: -1
	at org.mule.registry.AbstractRegistry.initialise(AbstractRegistry.java:113)
	at org.mule.config.spring.SpringXmlConfigurationBuilder.createSpringRegistry(SpringXmlConfigurationBuilder.java:135)
	at org.mule.config.spring.SpringXmlConfigurationBuilder.doConfigure(SpringXmlConfigurationBuilder.java:90)
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:43)
	... 10 more
Caused by: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location [classpath:midas_outbound_flow.xml]
Offending resource: URL [file:/Users/Jon-Elliott/workspace/midas_outbound_flow/target/test-classes/MIDAS_Outbound_Flow_test.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [midas_outbound_flow.xml]; nested exception is java.lang.ArrayIndexOutOfBoundsException: -1
	at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:68)
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:85)
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:76)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.importBeanDefinitionResource(DefaultBeanDefinitionDocumentReader.java:248)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseDefaultElement(DefaultBeanDefinitionDocumentReader.java:199)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:184)
	at org.mule.config.spring.MuleBeanDefinitionDocumentReader.parseBeanDefinitions(MuleBeanDefinitionDocumentReader.java:56)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:147)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:101)
	at org.mule.config.spring.MuleHierarchicalBeanDefinitionParserDelegate.handleSpringElements(MuleHierarchicalBeanDefinitionParserDelegate.java:180)
	at org.mule.munit.runner.mule.context.MunitBeanDefinitionParserDelegate.parseCustomElement(MunitBeanDefinitionParserDelegate.java:42)
	at org.mule.munit.runner.mule.context.MunitBeanDefinitionParserDelegate.parseCustomElement(MunitBeanDefinitionParserDelegate.java:96)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1422)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:193)
	at org.mule.config.spring.MuleBeanDefinitionDocumentReader.parseBeanDefinitions(MuleBeanDefinitionDocumentReader.java:56)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:147)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:101)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:495)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:335)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:303)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
	at org.mule.munit.runner.mule.context.MunitApplicationContext.loadBeanDefinitions(MunitApplicationContext.java:93)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:539)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:451)
	at org.mule.config.spring.SpringRegistry.doInitialise(SpringRegistry.java:86)
	at org.mule.registry.AbstractRegistry.initialise(AbstractRegistry.java:105)
	... 13 more
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [midas_outbound_flow.xml]; nested exception is java.lang.ArrayIndexOutOfBoundsException: -1
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:413)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:335)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:303)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.importBeanDefinitionResource(DefaultBeanDefinitionDocumentReader.java:242)
	... 37 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at org.apache.xerces.util.XMLAttributesImpl.addAttribute(Unknown Source)
	at org.mule.munit.runner.mule.context.MunitDomParser.startElement(MunitDomParser.java:45)
	at org.apache.xerces.parsers.AbstractDOMParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.mule.munit.runner.mule.context.MunitDocumentLoader.loadDocument(MunitDocumentLoader.java:46)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:389)
	... 42 more

The munit test runs with Maven.

**Comment by jon-elliott** [comment]
Update : Ditched (is there) Anypoint studio and use the plugin in eclipse luna its a bit more stable.
