### ISSUE TITLE
Executing mUnit tests in Anypoint Studio 5.1.2

### ISSUE THREAD

**Issue by karlignatius** [mulesoft/munit#196]
I have an application where the mUnit test execute correctly in Anypoint Studio 4.1.1, Mule EE, 3.5.1 EE and mUnit Runtime 3.4-M2)

I open this application in Anypoint Studio 5.1.2, Mule 3.5.1 EE and mUnit Runtome 3.5-M3-SNAPSHOT) and get the following errors when trying to execute my mUnit tests:

Configuration problem: Failed to import bean definitions from URL location [classpath:iag.mule.cpf.xml]
Offending resource: URL [file:/C:/Development/IAG/Mule/IAG.Mule.CPF/target/classes/iag.mule.cpf-test.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [C:\Development\IAG\Mule\IAG.Mule.CPF\target\classes\nz\co\utilities\iag\ProjectProperties.class]; nested exception is java.lang.IllegalArgumentException (org.mule.api.lifecycle.InitialisationException)
	at org.mule.munit.runner.mule.MunitSuiteRunner.<init>(MunitSuiteRunner.java:48)
	at org.mule.munit.runner.remote.MunitRemoteRunner.run(MunitRemoteRunner.java:40)
	at org.mule.munit.runner.remote.MunitRemoteRunner.main(MunitRemoteRunner.java:143).

I ran the tests on a different dev machine and got the same results.

**Comment by damiansima** [comment]
Hi @karlignatius , 

I would advise, as a first step, to upgrade to MUnit 3.5-M3-SNAPSHOT as it seems to be a compatibility error.
On the other hand the error it self seems to be related to one of your classes ProjectProperties.class. 
The error it self is not quite descriptive though :(

**Comment by karlignatius** [comment]
Hi

Anypoint Studio by default uses MUnit 3.5-M3-SNAPSHOT (see my original log). Is there anything else I can try? Just a a note, Before I received the error above, the code complained about another class. I removed it and now it is complaining about ProjectProperties.class. I am sure if I removed the ProjectProperties.class it will complain about next one in the package.

**Comment by damiansima** [comment]
@karlignatius, would you mind sharing your code? 

FYI you can mavenize the code and tell the project and change the MUnit runtime

**Comment by karlignatius** [comment]
I have not had feedback on sharing the code, but I will first have a look if I can solve this problem using Maven.
